# 特别提示：调试完成后请记得将debug改为false
debug: false

#用户组配置
##################################################
# 温馨提示：请仔细注意每个模板是属于哪个任务类型的配置！##
##################################################
users:
  # 第一个用户配置
  # 以下配置为工作日志
  # 这里默认仅适配宜宾学院，其他学校自行修改
  - user:
      # 任务类型（收集：0、签到：1、查寝：2、教师工作日志：3）
      type: 0
      #school 学校全称
      schoolName: 昆明学院
      #username 学号或者工号
      username: ''
      #password 密码
      password: ''
      # 地址信息
      address: '云南省昆明市五华区普吉路'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码
      sendKey: ''
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 102.680877
      #lat 纬度
      lat: 25.076813
      checkTitle: 1

      # 表单信息
      forms:
        - form:
            title: 今天你的所在地是？
            value: xx省/xx市/xx区
        - form:
            title: 今天你的体温是多少？
            value: 37.2℃及以下
        - form:
            title: 今天你的身体状况是？
            value: 健康
        - form:
            title: 近14天你或你的共同居住人是否有疫情中、高风险区域人员接触史？
            value: 否
        - form:
            title: 近14天你或你的共同居住人是否和确诊、疑似病人接触过？
            value: 否
        - form:
            title: 近14天你或你的共同居住人是否是确诊、疑似病例？
            value: 否
        - form:
            title: 你或你的共同居住人目前是否被医学隔离？
            value: 否
        - form:
            title: 今天你当地的健康码颜色是？
            value: 绿色
        - form:
            title: 本人是否承诺以上所填报的全部内容均属实、准确，不存在任何隐瞒与不实的情况，更无遗漏之处
            value: 是
